### PR TITLE
BZ 1278756 - Isn't possible to move group of elements from container

### PR DESCRIPTION
**Pull request by tsurdilo**
@krisv 

JS update to dragging / dropping logic. added case for cross-container moves while keeping everything else in tact as before.

### CODE REVIEW

**Comment by jlindop** [comment]
+1

**Comment by psiroky** [comment]
I know these are JavaScript changes, but could we add a test case? There surely must be ways to unit test JavaScript stuff.

**Comment by tsurdilo** [comment]
@psiroky i have added rhino locally for unit testing but we need to first discuss if that is what team wants to do and at this point will take me some time to make sure it all works and create a doc on how to write  the js based unit tests. I could for now create a test case in our Java tests that mimics this if really needed.

**Comment by porcelli** [comment]
@tsurdilo we, as a team, agreed from now on all code has to be tested. unless has a good reason for not

**Comment by tsurdilo** [comment]
@porcelli yes I know however I don't think we agreed on what tool(s) we will use for JS testing within our codebases, have we? I can keep working on adding rhino because I am familiar with if everyone is OK with that. I don't know the estimate atm how long it will take me to get that part working for all parts of the JS code in Designer so I guess until then this PR will stay open...

**Comment by krisv** [comment]
We have to make some decisions on where we want to spend our time on and how.  Building a new test framework for code we are putting into maintenance and where we are shifting strategy in the long run (to be more in line with how the rest of the workbench works) might not be worth the effort.  We discussed this before and decided to make an exception for fixes in the designer JS code, so we can focus on refactoring instead.  I agreed with Christian that I would take care of merging these PRs.

**Comment by porcelli** [comment]
@krisv @tsurdilo so... I wasn't aware of a general agreement that JS wouldn't be tested - I was considering that would be a case (PR) by case. That's fine.

**Comment by krisv** [comment]
Merged http://github.com/droolsjbpm/jbpm-designer/commit/a1577332a

**Pull request closed without merging**
