### PR TITLE
RHBPMS_2051, 350: Fix display of i18n process and element names in si…

### PR DESCRIPTION
**Pull request by jlindop**
…mulation tab

### CODE REVIEW

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
-1, sorry, test missing for fix in SimulationServlet. I do understand the desire to not test this given the convoluted logic in doPost (which also badly needs code formatting fixed) but we need to try and clean this up.

**Comment by jlindop** [comment]
@csadilek  Thanks for the reminder! Unit test added - its omission was just an oversight. We're looking into reformatting the code as there are other files in designer which also need it.

**Comment by csadilek** [comment]
+1

**Pull request merged**
