### PR TITLE
JBPM-5512 - Make it possible to move the components with the arrow keys

### PR DESCRIPTION
**Pull request by tsurdilo**
In addition to 
(windows - ctrl-shift, mac - option) p and m for property window and shape menu open/close
users can now move shapes around by selecting them and using the ctrl+shift/option + up/down/left/right arrows  to move shapes (or group of shapes) around the canvas. 

small video here: https://streamable.com/nkbl9
(in the video i used ctrl+shift/option + a to select all shapes, also a key binding)

### CODE REVIEW

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
@tsurdilo This works nicely by using the Alt key + up/down/left/right.
If you move some shapes like this then click 'Save', the notification pops up 'Process contains no changes since last save'.

**Comment by tsurdilo** [comment]
@jlindop nice catch! i will amend

**Comment by tsurdilo** [comment]
@jlindop saving after move ok now.

**Comment by jlindop** [comment]
Thanks. Ready to merge when test completes.
+1

**Comment by tsurdilo** [comment]
VFSRepositoryGitFileSystemTest runs fine locally. this pr does not contain any code that could break will keep looking

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
test fail seems related to uf change https://github.com/uberfire/uberfire/commit/2df8a950d2cf93816714ec8b0abfe18b223ed419

**Comment by tsurdilo** [comment]
amended with test fix

**Comment by tsurdilo** [comment]
@csadilek this has a +1 from previous comment by @jlindop - i added the fix for a test we talked about. Let me know if it's ok to merge. thanks

**Pull request merged**
