### PR TITLE
JBPM-5007: stop showProcessDocs function from being called multiple t…

### PR DESCRIPTION
**Pull request by jlindop**
…imes when not needed. This was impacting performance noticeably in IE11.

### CODE REVIEW

**Comment by csadilek** [comment]
Needs a review. @tsurdilo, maybe?

**Comment by tsurdilo** [comment]
@jlindop any reason you changed 

document.getElementById("processdocframe").contentWindow.showProcessDocs();
to
this.processDocContentPanel.items.get('processdocframe').getEl().dom.contentWindow.showProcessDocs();

your approach uses extjs lib which maybe is better to start avoiding if possibl

other than this  +1

**Comment by jlindop** [comment]
@tsurdilo I was getting exceptions when developing this at first, hence the extra 'if ()' clauses and long-winded way of calling showProcessDocs(). It's working now with the simplified call to showProcessDocs(), so that's a good catch (:

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
master: 3d53541e6686c3db5e49bd70c467bc137bcda6f7

**Pull request closed without merging**
