### PR TITLE
Bug 1304447 - [GSS](6.2.z) Not able to select specific branch from repository

### PR DESCRIPTION
**Pull request by Rikkola**
https://github.com/droolsjbpm/guvnor/pull/264
https://github.com/droolsjbpm/kie-wb-common/pull/278
https://github.com/droolsjbpm/drools-wb/pull/132
https://github.com/droolsjbpm/jbpm-console-ng/pull/341
https://github.com/droolsjbpm/jbpm-designer/pull/161
https://github.com/droolsjbpm/jbpm-form-modeler/pull/38
https://github.com/droolsjbpm/optaplanner-wb/pull/38
https://github.com/droolsjbpm/kie-wb-distributions/pull/209

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
Not sure if I can fire that :)

**Comment by csadilek** [comment]
master: c6af29a81416e89c9a75a984135189139b539018

**Pull request closed without merging**
