### PR TITLE
JBPM-5278: added tests and refactoring done

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
This PR includes tests from #392. Next it simplifies injection and passing of some beans. @tsurdilo @jlindop would you mind to take a look?

**Comment by tsurdilo** [comment]
@jomarko I'm still testing this . will finish asap!

**Comment by jomarko** [comment]
@tsurdilo no problem, just let me know if you find any problem.

**Comment by csadilek** [comment]
@tsurdilo do you have an update on this? thx.

**Comment by tsurdilo** [comment]
@csadilek just finished testing  +1 . thanks

**Pull request merged**
