### PR TITLE
JBPM-5190: constant assignments fixed for call activity

### PR DESCRIPTION
**Pull request by jomarko**
Please merge #328 at first.

### CODE REVIEW

**Comment by jlindop** [comment]
@jomarko I get a couple of merge conflicts with this commit, after PR328 has been merged.

**Comment by jomarko** [comment]
@jlindop I rebased my commit with new 6.5.x branch right now, let's see result of jenkins job.

**Comment by jomarko** [comment]
@jlindop all conflicts removed.

**Comment by jlindop** [comment]
@jomarko Thanks.
+1

**Pull request merged**
