### PR TITLE
BZ1297383: Add style property with height and width to PDF created by…

### PR DESCRIPTION
**Pull request by jlindop**
… "Share Process PDF" menu option

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jlindop same comment for this as in https://github.com/droolsjbpm/jbpm-designer/pull/191

**Comment by jlindop** [comment]
@tsurdilo  Modified according to your comment on  #191. Thanks

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
6.4.x: 48219691cb2ec3742fd0c915c75718fda799c3b6

**Pull request closed without merging**
