### PR TITLE
JBPM-4918: marshaling tests, index out of boundary fixed (6.4.x)

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
@jlindop , @tsurdilo please can you take a look if you have a moment?

**Comment by jlindop** [comment]
@jomarko 
Hi Jozef, I'm not clear what "index out of boundary fixed" in the title means - was there an Exception being thrown somewhere that is fixed now?

**Comment by jomarko** [comment]
@jlindop some tests I have added with this PR was failing because of this piece of code: "sb.setLength(sb.length() - 1);" There was originally no check if sb.length() is bigger than 0

**Comment by jlindop** [comment]
@jomarko  Thanks. Some nice code cleanup here.

+1

**Comment by csadilek** [comment]
6.4.x: 0dd943869ff13a39b2289f27e1f4134e7476d929

**Pull request closed without merging**
