### PR TITLE
RHBPMS-4200: Boundary event doesn't store multi line names if element with event lay inside of subprocess

### PR DESCRIPTION
**Pull request by hasys**
and tests clean up: BPMN2 Unmarshalling tests enable, fix and synchronization with master branch.

### CODE REVIEW

**Comment by hasys** [comment]
Hi @jlindop, @tsurdilo ,

can I ask you to review this PR? There are some changes: 

1. Rename test class with "TestCase" ending due to maven runs tests with "Test" ending only;
2. Fix for failing tests after 1 and tests synchronization with Master branch;
3. Move Bpmn2UnmarshallingTest and resources to appropriate package;
4. Fix and tests for RHBPMS-4200 and related issues with multi-line elements names.

**Comment by jlindop** [comment]
The Jira entry https://issues.jboss.org/browse/RHBPMS-4200 doesn't have a Target Release or the required ACK's, so I guess it's premature to fix this on 6.5.x.

**Comment by hasys** [comment]
Hi @jlindop,
thank you for your review. I guess we can try to raise this issue because it's a trivial fix or I can revert product code changes and retain just tests changes. Because without this changes Unmarshaller tests are not running on Jenkins at all.

**Comment by jlindop** [comment]
Hi @hasys, Today RHBPMS-4200  has target release set to 6.4.0.GA, so I'll review when the Jira has all the ACK's.

**Comment by hasys** [comment]
Hi @jlindop the Jira has all the ACK's do you have a time to review it?

**Comment by jlindop** [comment]
Looks good and tested ok - thanks.
+1

**Pull request merged**
