### PR TITLE
Upgrade to GWT 2.8.0-rc1

### PR DESCRIPTION
**Pull request by csadilek**
Needs:

droolsjbpm/droolsjbpm-build-bootstrap#250
errai/errai#184
uberfire/uberfire#461

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (but ```ecj``` comment probably needs investigating as suggested by @psiroky)

**Comment by csadilek** [comment]
ecj comment removed

**Comment by manstis** [comment]
+1 to merge (when green).

**Comment by csadilek** [comment]
Verified that the test failure is unrelated. It happens with and without the commits in this PR series.

**Comment by csadilek** [comment]
@tsurdilo verified that this tests will be fixed in https://github.com/droolsjbpm/jbpm-designer/pull/377

**Pull request merged**
