### PR TITLE
Some minor findbugs fixes

### PR DESCRIPTION
**Pull request by Hasys**
Cherry-Pick for master branch PR https://github.com/droolsjbpm/jbpm-designer/pull/76

### CODE REVIEW

**Comment by tsurdilo** [comment]
-     if (tagsToInsert != "") {
+                        if (tagsToInsert.equals("")) {

seems to be a bug here (there are couple of places in the same class like this).

**Comment by Hasys** [comment]
@tsurdilo Fix for this bug is there https://github.com/droolsjbpm/jbpm-designer/pull/89 after review this PR will be also proposed for 6.3 branch. Also I can remove this changes from this commit.

**Comment by porcelli** [comment]
@Hasys  @tsurdilo is this still makes sense?

**Comment by tsurdilo** [comment]
@porcelli I think it's no longer but just confirming with @Hasys as well

**Comment by Hasys** [comment]
@porcelli @tsurdilo With addition commit just merged to master brunch make sense. It commit have fix for mistake in this commit and addition enhancements. I attached it to this PR. Merged commit: https://github.com/droolsjbpm/jbpm-designer/pull/106#event-488440220

**Comment by porcelli** [comment]
@tsurdilo mind review?

**Comment by porcelli** [comment]
@Hasys @tsurdilo just noticed.. sorry, but 6.3.x is blockers only now. I think we'll have to close this now

**Comment by Hasys** [comment]
@porcelli OK, so in this case it's makes no sense now.

**Pull request closed without merging**
