### PR TITLE
JBPM-5416 - Update workitem configuration to allow for default values…

### PR DESCRIPTION
**Pull request by tsurdilo**
… of some / all parameters

### CODE REVIEW

**Comment by tsurdilo** [comment]
compilation errors from jenkins build not related to jbpm-designer and this PR

**Comment by tsurdilo** [comment]
@jlindop the changes are shown in this video: https://streamable.com/1nqt

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by jlindop** [comment]
@tsurdilo  The custom editors work nicely, but if you set some values in them, then save, close & re-open the BP, change the values, save, close & re-open the BP again, the first set of values which were set are still there  https://streamable.com/a9r3

**Comment by tsurdilo** [comment]
@jlindop nice catch - amended. please retest when you can. thanks.

**Comment by jlindop** [comment]
Thanks - this works fine now.
+1

**Pull request merged**
