### PR TITLE
JBPM-5711 - elementname stored in default charset other than UTF-8 in…

### PR DESCRIPTION
**Pull request by tsurdilo**
… bpmn2

### CODE REVIEW

**Comment by tsurdilo** [comment]
jenkins please retest this

**Comment by tsurdilo** [comment]
@krisv @manstis Hi guys, could we get someone to please review this? Thanks!

**Comment by tsurdilo** [comment]
@manstis for reads i see we use IOService readAllBytes which i assume already does that and ioService.readAllString where this code already pases the encoding. If I'm missing something please show me line number so I understand. Thanks.

**Comment by manstis** [comment]
@tsurdilo Great.. remember I don't _know_ the code as intimately as you; so I might ask stupid questions based on what I can see in the PR! Thanks for the pointers.

**Pull request merged**
