### PR TITLE
GUVNOR-2415: Boundary events lose it’s documentation after save and r…

### PR DESCRIPTION
**Pull request by hasys**
…eopen Business Process

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys thanks for this. may i just ask why all these changes are needed just for the 1 liner 
 
   be.getDocumentation().addAll(beEntry.getDocumentation());

?

**Comment by hasys** [comment]
Hi, @tsurdilo . We need two times 
`be.getDocumentation().addAll(beEntry.getDocumentation());`
because for first time we have to copy documentation during IntermediateEvent->BoundaryEvent migration and the second time while it looking for BoundaryEvent container. Also there are another minor fix for EventDefinitions (it was checked is BoundaryEvent instance of EventDefinition, but it never true).

Another 7 lines just changed "\t"->"    " and diamond notice introduced (master branch is prepared for JDK8+ so we can do this.

All remaining lines is a try to merge Event copying in one method but it is not so easy because for first time it is CatchEvent->BoundaryEvent migration and for the second time it is BoundaryEvent->BoundaryEvent cloning. But I started migration with small step. After this and https://github.com/droolsjbpm/jbpm-designer/pull/157 will be merged I will continue this effort. But for now this minor refactoring at least will speed up unmarshalling for a little.

**Comment by psiroky** [comment]
@hasys could you please rebase this on top of the current master and fix the merge conflicts (they arose after merging your other PR)?

**Comment by hasys** [comment]
@psiroky done.

**Comment by psiroky** [comment]
@hasys thanks! I'll merge this once the build succeeds.

**Pull request merged**
