### PR TITLE
BZ1275868: Cannot add boundary event for user task, +refactoring

### PR DESCRIPTION
**Pull request by Hasys**
if we have multiple subprocesses with boundary event

### CODE REVIEW

**Comment by Hasys** [comment]
Commit from master branch: https://github.com/droolsjbpm/jbpm-designer/commit/6362b7770036071dcb87ab18db285c819b5c4e43

**Comment by csadilek** [comment]
@jlindop @tsurdilo hi guys, please review incoming commits even if they were cherry-picked from another branch. Once you plus one them, they will be merged.

**Comment by tsurdilo** [comment]
I can't see the diff in Bpmn2JsonUnmarshaller.java and is it really necessary for the BZ to do all the moves of json files? I would do that in a separate PR because I don't think those moves are related to the BZ. 

Need the diff for Bpmn2JsonUnmarshaller.java

**Comment by Hasys** [comment]
Removed package reorganization. Diff is visible now. Getting rid of useless tabulations moved to separate commit.

**Comment by tsurdilo** [comment]
@Hasys thanks for doing this. compared the bpmn2 before/after and looks good. tests look good. 

+1

**Comment by csadilek** [comment]
6.4.x: 0797757ed5505f84965350d7ff66ff0e29a95e9f and 3b9b3717209af85fda2da1a1569100bda326be1f

**Pull request closed without merging**
