### PR TITLE
JBPM-4908  Add zanata.xml config file to jbpm-designer-api module

### PR DESCRIPTION
**Pull request by jlindop**
Added after discussion with Michael Biarnes Kiefer.

### CODE REVIEW

**Comment by manstis** [comment]
Is there a very good reason why there's i18n in the -api module  (I assume possibly i18n for server - side generated messages shown on the client?).. otherwise it's questionable why an -api module needs Zanata configuration.

**Comment by jlindop** [comment]
@manstis Yes, designer has a set of messages in the api module which are shown on the client.  The zanata.xml file was added to the 6.3.x branch, and I guess the fact that it wasn't also added on master was accidental.

**Comment by manstis** [comment]
Fair enough, I appreciate that. 

I was just a little surprised that an -api module needs Zanata configuration and perhaps it highlights that the i18n constants would be better stored in the -client (or -backend module - I suspect Designer includes the i18n constants in a download for Oryx from a Servlet or similar)...

**Comment by mbiarnes** [comment]
I did another test, like bespoken with Neus.
The steps to do Zanat translation updates in jbpm-designer are:
in root directory mvn zanata:pull-module; mvn replacer:replace -N
then cd into jbpm-designer-api and do again replacer:replace -N.
This works without this zanata.xml.
Before we applied the ascii2ascii and did in jbpm-designer-api a mvn zanata:pull-module again, therefor we needed the xml - but the preocedure changed a bit.
I think this PR can be closed and not merged in.
Sorry for the caused inconveniences.

**Comment by jlindop** [comment]
@mbiarnes - Closing without merging, as suggested.

**Pull request closed without merging**
