### PR TITLE
GUVNOR-2379 - Overview tab saving is not working

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by jlindop** [comment]
@tsurdilo  https://github.com/droolsjbpm/jbpm-designer/pull/215 has been merged this morning (Use Base64 class from commons-codec intead of own Base64Backport) and after this, DefaultDesignerAssetServiceTest fails to compile. (The reference to Base64Backport in this file need to be replaced with Base64,and the import of Base64Backport deleted).

**Comment by tsurdilo** [comment]
@jlindop amended

**Comment by jlindop** [comment]
+1

**Comment by manstis** [comment]
@tsurdilo Glad to see you found a (what looks like) simple solution :)

**Pull request merged**
