### PR TITLE
BZ1297383: Add style property with height and width to PDF created by…

### PR DESCRIPTION
**Pull request by jlindop**
… "Share Process PDF" menu option

### CODE REVIEW

**Comment by csadilek** [comment]
Needs a review, @tsurdilo?

**Comment by tsurdilo** [comment]
@jlindop I think finding the SVG width height by traversing the svg in backend is really overhead when you already get it for free from svg element returned from getSVGRepresentation in canvas.js

Once you get the svg representation you should be able to simply say:

getCanvas().getSVGRepresentation(false).getAttributeNS(null, 'width')
getCanvas().getSVGRepresentation(false).getAttributeNS(null, 'heght')

and pass it into transformer servlet. IMO this would be a better approach and more stable. WDYT?

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
master: 3db10a970d28b2fab32dac7da314ac8203216d65

**Pull request closed without merging**
