### PR TITLE
BZ 1298686 - Allow workflow patterns to include node properties

### PR DESCRIPTION
**Pull request by tsurdilo**
@jlindop - to test start designer and drag/drop the "Sequence with Data" Workflow pattern to the canvas. You will see that each node in the pattern has properties defined such as task type , colors, and assignments.

### CODE REVIEW

**Comment by jlindop** [comment]
Tested and looks good.
+1

**Comment by csadilek** [comment]
@tsurdilo seems there's an easy opportunity to not duplicate the new code in patterncreator.js and add a method instead?

**Comment by tsurdilo** [comment]
@csadilek done and amended. thanks!!

**Comment by csadilek** [comment]
Thanks.

master: a76ac4c72d6aca64e3b667db6a1ced18bd6a4137

**Pull request closed without merging**
