### PR TITLE
[6.5.x] RHBPMS-4130 - break possible script tag

### PR DESCRIPTION
**Pull request by tsurdilo**
@hasys fixes the issues you reported on https://issues.jboss.org/browse/RHBPMS-4131

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys amended to include your latest find in the process sim timeline

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by hasys** [comment]
Looks good, can't reproduce it in standalone Designer. +1
Jenkins fail is not related with changes.

**Comment by tsurdilo** [comment]
jenkins retest this

**Pull request merged**
