### PR TITLE
_dev_BZ-1320054: dockers of edges inside of subprocesses are moving now

### PR DESCRIPTION
**Pull request by jomarko**
Hello both @jlindop and @tsurdilo. Please can you have a look on this? I think that I have resolved the issue filed in BZ-1320054. But I am not javascript expert. I was just searching for different keywords in source code for a long time. 

Even if this PR won't be merged, I hope that it will help you in solving the BZ-1320054.

### CODE REVIEW

**Comment by jlindop** [comment]
@jomarko Is "BZ-1320054" the right BZ number for this PR? I'm wondering whether it's addressing a different BZ.

**Comment by jomarko** [comment]
I think it is right BZ number. If you read last comment there. Anyway, I found that there is still problem if are dockers used for example on data object associations inside of subprocess. I am investigating it.

**Comment by jlindop** [comment]
@jomarko Thanks. I guess I'm not clear how this PR addresses BZ-1320054. As @tsurdilo has looked at this in the past, maybe he'll be able to review the PR when he comes online.

**Comment by jomarko** [comment]
I am closing this PR because proposed code change doesn't work properly, if there are used data objects and associations connected with them have dockers.

**Pull request closed without merging**
