### PR TITLE
[6.5.x] RHBPMS-1566 - Scripts with || are incorrectly saved

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by jomarko** [comment]
I think this piece of code is worth to extract into separate method. I found 9 occurrences in the Unmarshaller.


                String scriptLanguage;
                if(properties.get("script_language").equals("java")) {
                    scriptLanguage = "http://www.java.com/java";
                } else if(properties.get("script_language").equals("mvel")) {
                    scriptLanguage = "http://www.mvel.org/2.0";
                } else if(properties.get("script_language").equals("javascript")) {
                    scriptLanguage = "http://www.javascript.com/javascript";
                } else {
                    // default to java
                    scriptLanguage = "http://www.java.com/java";
                }

**Comment by tsurdilo** [comment]
@jomarko agreed. would it be ok to make that part of a refactoring PR separate from this? I can get that in asap.

**Comment by jomarko** [comment]
@tsurdilo I am fine with refactoring in separate PR, if the new PR will me applied as for master so for 6.5.x. Refacotring only one branch could cause problems during cherry-picking between these two branches. So, do you plan to refactor both branches?

**Comment by jlindop** [comment]
Tested and works well, so ready to approve if the refactoring discussed above is done separately.

**Comment by tsurdilo** [comment]
@jomarko I will create a jira for it and it will be included whenever a release asks for it. I understand the value of refactoring this code but 
* it is not part of the fix for this platform jira
* it has been around for a number of years and does not right now for this jira add particular value for it
* it will be in master as soon as we get our other priority jiras in place for the next release

HTH

**Comment by jomarko** [comment]
+1 from myself, probably also from @jlindop according to his previous comment.

**Comment by csadilek** [comment]
I don't understand why this can't be refactored now. It looks like a matter of minutes to me. We certainly shouldn't be postponing the refactoring to (maybe) the next release. There's always gonna be something that will look to be more important than the refactoring. So it will never get done. We have empirical evidence for that :).

**Comment by jomarko** [comment]
@csadilek @tsurdilo I am ready and willing to do the mentioned refactoring. Just let me know if I have green to do it as on master so for 6.5.x. I understand that @tsurdilo have a lot of work with other Jiras and I would like to help.

**Comment by csadilek** [comment]
@jomarko definitely a green light from my side ;). thanks.

**Comment by tsurdilo** [comment]
@jomarko same here :) was never a question if we do this or not, just in what pr and when. Thanks for your help!

**Pull request merged**
