### PR TITLE
JBPM-5104: both hints using lower case

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jlindop** [comment]
@jomarko The constants actually used in the UI are in jbpm-designer-api:
https://github.com/droolsjbpm/jbpm-designer/blob/master/jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants.properties,
so you need to update the string in there.

I'll email Tiho about this, as I'm not sure why we have the translations in jbpm-designer-client as well as jbpm-designer-api.

**Comment by jomarko** [comment]
Thanks @jlindop, I will amend this PR soonly.

**Comment by jomarko** [comment]
I think I replaced all occurrences now, please review @jlindop .

**Comment by jlindop** [comment]
+1

**Pull request merged**
