### PR TITLE
GUVNOR-2340 - Annotation for element inside subprocess fails validation

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@csadilek @manstis amended

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
6.4.x: ef99170222221202e449b0dd2fb5f9ca2c0cb7a9

**Comment by psiroky** [comment]
I've noticed just now (yeah too late :)), but the code uses `tab`s for indentation. We should only use spaces.

**Pull request closed without merging**
