### PR TITLE
(6.4.x) JBPM-5060: removed unused private method

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by csadilek** [comment]
6.4.x is in blockers-only mode, although I'd like to merge this...

**Comment by jomarko** [comment]
@jlindop @tsurdilo @csadilek, I think now the 6.4.x branch is not in blockers only mode. Can you have a look please?

**Comment by csadilek** [comment]
+1

**Comment by tsurdilo** [comment]
+1

**Pull request merged**
