### PR TITLE
BZ 1283135 - Changing of task type does not trigger Save dialogue

### PR DESCRIPTION
**Pull request by tsurdilo**
@csadilek 6.3.x PR (js changes only)

### CODE REVIEW

**Comment by csadilek** [comment]
@krisv can you confirm this for 6.3.x?

**Comment by krisv** [comment]
@csadilek @tsurdilo This should not go into master at this point (blockers only).

**Comment by porcelli** [comment]
@Hasys  @tsurdilo is this still makes sense?

**Comment by tsurdilo** [comment]
@csadilek This is now OK to put in for 6.2.1

**Comment by csadilek** [comment]
Thanks.

6.3.x: 70ff0d872ea6ad4c5694c50c0bab18171ff68200

**Pull request closed without merging**
