### PR TITLE
JBPM-4988: connectors with name, documentation or condition added int…

### PR DESCRIPTION
**Pull request by jomarko**
…o process documentation

### CODE REVIEW

**Comment by jomarko** [comment]
@tsurdilo @jlindop hello to all, this PR adds into process documentation connectors which have set 'name', 'documentation' or 'condition expression'. Problem of this PR is that if there is no such connector, there will be empty section 'Connectors' in section 'Element Details'. Do you have any idea how to enhance my PR? Thanks for any ideas.

**Comment by tsurdilo** [comment]
@jomarko I will look at this asap. also if we add connectors there needs to be a change to 
https://github.com/droolsjbpm/jbpm-designer/commit/1f23e8529ebb05ac9216008902e12478ba84a09e 
to also include Edges that i need to change too

**Comment by jomarko** [comment]
Hello @tsurdilo , I updated the method `findShapeWithId` to assume also ORYX Edges in addition to Nodes. Let me know what do you think.

https://github.com/jomarko/jbpm-designer/blob/4fd04925b7b88a1353cb5df1e80c4cbb4c5491bb/jbpm-designer-client/src/main/resources/org/jbpm/designer/public/js/Plugins/view.js#L2203-L2216

**Comment by tsurdilo** [comment]
@jomarko looks good. thanks
+1

**Pull request merged**
