### PR TITLE
JBPM-5007: stop showProcessDocs function from being called multiple t…

### PR DESCRIPTION
**Pull request by jlindop**
…imes when not needed.

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jlindop same comment as in https://github.com/droolsjbpm/jbpm-designer/pull/189

**Comment by jlindop** [comment]
@tsurdilo Same comment as in #189. Thanks

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
6.4.x: 0f4274204a004536b5eabb40f81e25c9eb67fa20

**Pull request closed without merging**
