### PR TITLE
JBPM-5095: default gate tests

### PR DESCRIPTION
**Pull request by jomarko**
Dependent on #337 . After needed PR will be merged, I will amend appropriately this PR.

### CODE REVIEW

**Comment by jomarko** [comment]
I think it is ready for review. Let's see result of jenkins job.

**Comment by jomarko** [comment]
Also let me know, if it is necessary for PR-ts to contain only one commit, then I can try to merge both commits into one.

**Comment by jomarko** [comment]
jenkins retest this please

**Comment by jlindop** [comment]
+1

**Pull request merged**
