### PR TITLE
Minor fix for properties names inconsistancy

### PR DESCRIPTION
**Pull request by Hasys**

### CODE REVIEW

**Comment by jlindop** [comment]
@Hasys 
The code change looks OK, but I'm not aware that it changes anything in the UI.
In the properties pane for activities, links etc., there is a property 'Font color', in which the use of lowercase 'c' in 'color' is inconsistent with other property names. It's probably worth creating a BZ for this inconsistency in property names so that all properties can be made to use consistent case.
(To change the property name in the UI,  it needs to be changed at
https://github.com/droolsjbpm/jbpm-designer/blob/master/jbpm-designer-api/src/main/resources/org/jbpm/designer/resources/i18n/DesignerConstants.properties#L1273 )

**Comment by Hasys** [comment]
@jlindop thank you for your notion. This PR fixed, new bugzilla created: https://bugzilla.redhat.com/show_bug.cgi?id=1287000

**Comment by jlindop** [comment]
@Hasys This looks good, and thanks for creating the new BZ.
+1

**Comment by csadilek** [comment]
master: 88db906e579e1310c04825312680b85327a5b80b

**Pull request closed without merging**
