### PR TITLE
JBPM-5134: Added tests for error boundary events

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
@jomarko this is in conflict now. Can you take a look. Also the commit message needs to be fixed "error error".

**Comment by jomarko** [comment]
@csadilek sure, I will fix it.

**Comment by jomarko** [comment]
Merge conflicts resolved.

**Comment by csadilek** [comment]
Thanks @jomarko.

**Pull request merged**
