### PR TITLE
designer-standalone: use shared GWT props + tweak memory/resource set…

### PR DESCRIPTION
**Pull request by psiroky**
…tings

@tsurdilo please take a look. I did test with "mvn clean install -Dfull" and "mvn clean gwt:run" as everything seems to work as expected.

### CODE REVIEW

**Comment by tsurdilo** [comment]
@psiroky tried as well. seems to work as you said here too

**Comment by psiroky** [comment]
@tsurdilo so you are OK with merging?

**Comment by tsurdilo** [comment]
@psiroky yes

**Comment by psiroky** [comment]
@tsurdilo please comment with "+1" if you agree with the changes in a particular PR. That makes sure the PR gets picked and merged by gatekeeper.

**Comment by tsurdilo** [comment]
+1

**Comment by csadilek** [comment]
Thanks!

master: 1b6e0115a62b28199263fc4b933d337e1e6b4c0f

**Pull request closed without merging**
