### PR TITLE
Some minor findbugs fixes

### PR DESCRIPTION
**Pull request by Hasys**
Findbugs found 640 bugs/warnings. There is fixes for 21 of them. Designer have a lot of false positive warnings, but some of them is very useful. We need to investigate it more deeper.

### CODE REVIEW

**Comment by csadilek** [comment]
+1, but waiting for @tsurdilo or @jlindop to approve.

**Comment by tsurdilo** [comment]
I would honestly prefer if we leave the uniDirectionalAssociations stuff in the code (comment it) rather than just deleting it. This is functionality that we started but did not finish yet so leaving it in the code as comments would be nice. Could you please update that part?

Other than that its great. Thank you as always for your contributions!

**Comment by csadilek** [comment]
@tsurdilo but that's what version control is for ;). You're not gonna lose the changes, you can always resurrect them from history. No need, imo, to leave them in the code but commented out.

**Comment by Hasys** [comment]
@csadilek +1 @tsurdilo If we can merge it I will create PR for 6.3.x branch

**Comment by tsurdilo** [comment]
@csadilek @Hasys I honestly didn't think this was a big request but be as it may. It is perfectly fine the way it is now. Thanks!

+1

**Comment by csadilek** [comment]
Thanks!

master: 7392209c0b9b59bd0e4eb0bd78de86eb87cca8c6

**Pull request closed without merging**
