### PR TITLE
RHBPMS-4130 - break possible script tag

### PR DESCRIPTION
**Pull request by tsurdilo**
@hasys fixes the issues you reported on https://issues.jboss.org/browse/RHBPMS-4131

### CODE REVIEW

**Comment by tsurdilo** [comment]
@hasys amended to include your latest find in the process sim timeline

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by hasys** [comment]
Looks good, thanks! +1

**Comment by csadilek** [comment]
To be picky, would've been nicer to create a reusable method instead of duplicating the two replace statements 7 times.

**Pull request merged**
