### PR TITLE
Refactoring required by page Table extract

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by ederign** [comment]
@psiroky this is related with errai test?

**Comment by psiroky** [comment]
@ederign yes. I created https://github.com/errai/errai/pull/164 which fixes this. Just need someone to merge it :)

**Comment by jlindop** [comment]
@ederign  Thanks for this - at least local builds work now.
+1

**Comment by csadilek** [comment]
master: 0dec21aa5bc986e1381ee75c897ffc8be8e8659a

**Pull request closed without merging**
