### PR TITLE
GUVNOR-2502: Consolidate client-side bootstrap logic in various workbench implementations

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
To merge together with:

https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/202
https://github.com/uberfire/uberfire/pull/372
https://github.com/droolsjbpm/kie-wb-common/pull/360
https://github.com/droolsjbpm/jbpm-form-modeler/pull/50
https://github.com/droolsjbpm/drools-wb/pull/176
https://github.com/droolsjbpm/jbpm-designer/pull/256
https://github.com/droolsjbpm/jbpm-console-ng/pull/421
https://github.com/droolsjbpm/optaplanner-wb/pull/69
https://github.com/droolsjbpm/livespark/pull/22
https://github.com/droolsjbpm/kie-wb-distributions/pull/285

**Comment by paulovmr** [comment]
jenkins please retest this

**Comment by paulovmr** [comment]
jenkins please retest this

**Comment by csadilek** [comment]
+1

**Pull request merged**
