### PR TITLE
Fix some findbugs warnings

### PR DESCRIPTION
**Pull request by jhrcek**
Please also cherry pick to 6.3.x if this PR is acceptable.

### CODE REVIEW

**Comment by psiroky** [comment]
@tsurdilo any update on this? Can it be merged?

**Comment by csadilek** [comment]
+1, some of these fixes are actually really important i.e. the equals fix and should be merged. What do you think @tsurdilo?

**Comment by tsurdilo** [comment]
+1 looks god. Thank you!

**Comment by csadilek** [comment]
Thanks!

master: 5ede3f31f4edd779c1b5245d7cd836adf115db66

**Pull request closed without merging**
