### PR TITLE
BZ 1277883 

### PR DESCRIPTION
**Pull request by tsurdilo**
@jlindop @csadilek @manstis 

PR for BZ 1277883 - check if global directory is present before trying to create it . Same for the default workitem definition

### CODE REVIEW

**Comment by manstis** [comment]
I know the issue, I see the solution.. unfortunately I don't see any tests :(

**Comment by tsurdilo** [comment]
@manstis It is hard to have Designer-specific tests for new project creation within the designer code itself. I can add tests in kie-wb do you think that would be better?

**Comment by manstis** [comment]
This is true, if you're looking at an integration test, but for a unit test you could manually invoke the ```createGlobalDirOnNewProject()``` method and check (1) the global files are only created once and (2) no ```FileAlreadyExistsException``` error is thrown.

**Comment by csadilek** [comment]
Yes, it should be relatively easy to write a unit test for this method. Can you please add the test @tsurdilo?

**Comment by tsurdilo** [comment]
@csadilek @manstis 
test added

**Comment by tsurdilo** [comment]
@csadilek I would like to go through all the tests and fix the assertNotNull where needed since the place/test in question is not related to this commit (is some old test). I think for the second comment the test should fail if that exception is thrown so it's good as it is now I think.

**Comment by tsurdilo** [comment]
Changed the assert as requested and squashed commits into one.

**Comment by csadilek** [comment]
+1, thanks for updating the tests @tsurdilo . @manstis do you want to take a look again, before I merge?

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: b665841062851844b4f6fc8757555edff58f5049

@tsurdilo, just a reminder if you want this for 6.3.x as well, please send a separate PR.

**Pull request closed without merging**
