### PR TITLE
removed @author tag

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by jlindop** [comment]
@mbiarnes Hi Michael. There are still quite a lot of @ author tags in the source, some for team members, e.g. 'Tihomir Surdilovic' (also 'Surdilovic') and some others who I don't know, e.g 'Antoine Toulme', 'Falko Menge'. Some of these are in .java files and some in .js and .jsp files. Is this intentional?

**Comment by tsurdilo** [comment]
@jlindop I think if they are not in @author tags they can be left as is?

**Comment by mbiarnes** [comment]
@jlindop I am aware of this. I don't know exactly the politics in Red Hat about the author tag, but I think we can't take out names that are not from Red Hat. So I took out surdilovic - in case his name apperead alone. In cases where it appears with another name (Antoine Toulme) I 
didn't remove it -

**Comment by jlindop** [comment]
@mbiarnes Thanks for the clarification.
+1

**Comment by tsurdilo** [comment]
@mbiarnes that sounds good - thanks! +1

**Comment by jlindop** [comment]
Ready to merge
+1

**Pull request merged**
