### PR TITLE
JBPM-4978 - Process Documentation contains encoded values

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by jlindop** [comment]
@tsurdilo   If the constant contains a space, e.g. "ab cd+ef" , this is displayed as "ab+cd+ef" in the Process Doc tab because it's encoded as "ab+cd%2Bef" in the json, which decodeURIComponent decodes to "ab+cd+ef". To handle this, replacing decodeURIComponent(escapedp) with  
decodeURIComponent(escapedp.replace(/\+/g, ' '))   should work.

**Comment by tsurdilo** [comment]
@jlindop amended (and https://github.com/droolsjbpm/jbpm-designer/pull/203 too)

**Comment by jlindop** [comment]
+1

**Comment by csadilek** [comment]
master: d9dbc2fa93be0d19de01cf1e8cc095ad9a03e18f

**Pull request closed without merging**
