### PR TITLE
(6.4.x) JBPM-5031: NPE prevented and code extracted to private methods

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
Please, do not merge yet, I have to add tests.

**Comment by jhrcek** [comment]
Be careful, some instances of removed code have `if (processingTime == null) { continue;}` which is not included in the extracted private method `extractTimeParamsToProperties`

**Comment by jomarko** [comment]
@jhrcek, I know, I will change `extractTimeParamsToProperties` also a little bit.

**Comment by jomarko** [comment]
I am still in progress.

**Comment by jomarko** [comment]
Hello @tsurdilo , @jlindop , @hasys . I am facing problem in writing tests for this PR. I have problem on this line of code [1]. In each test method of class "Bpmn2JsonMarshallerTest" it returns empty list, even if there are simulation data in process. I spent with this 2 days and I can't find out, where is the problem. In running business central I can find simulation data in json of given process. So do you have any idea what is difference in creating json of process in running business central and in our tests? Thanks for any help.

[1]
https://github.com/jomarko/jbpm-designer/blob/JBPM-5031/jbpm-designer-backend/src/main/java/org/jbpm/designer/bpmn2/impl/Bpmn2JsonMarshaller.java#L101

**Comment by jomarko** [comment]
I solved my problem. Tomorrow I will add a little bit more testcases and I will mark this issue ready for review. I know that 6.4.x is in blockers only mode, however I will cherry pick this at least to master.

**Comment by jomarko** [comment]
Ready for review.

**Comment by jomarko** [comment]
@jlindop @tsurdilo @csadilek, I think now the 6.4.x branch is not in blockers only mode. Can you have a look please?

**Comment by jlindop** [comment]
If 6.4.x is not in blockers mode,   +1

**Comment by jomarko** [comment]
@jlindop thanks for your review, unfortunately I have to close this PR. I will cherry pick again when 6.5.x branch appears

**Pull request closed without merging**
