### PR TITLE
Unmarshaller bugfix and refactoring

### PR DESCRIPTION
**Pull request by Hasys**
@tsurdilo this PR contain refactoring of Bpmn2JsonUnmarshaller#revisitBoundaryEventsPositions. It turned out that it was no way to meet NullPointerException so it check not needed at all. Also there was a Filed bag and I have pair of question which I will add to appropriate lines.

### CODE REVIEW

**Comment by tsurdilo** [comment]
@Hasys yes the copy is needed. missing to copy documentation tho should be added. nice catch.
I will review this in more detail asap

**Comment by tsurdilo** [comment]
@Hasys if you are looking at the extension element code already one thing maybe to look at is to create util method for that (we use this in a lot of places in marshaller/unmarshaller). That would be helpful

**Comment by Hasys** [comment]
@tsurdilo yes I agree. And also, I going to PTO now, so if this PR is fine it could be really good if we merge this PR without remaining little things and fix it in additional commits. But if it contain some big problems I can to fix it during next week only :(

**Comment by Hasys** [comment]
@tsurdilo Hi Tihomir. Is this PR good enough to merge or I have to change something for it? I guess it is not so good just make rebase time by time. I would like to merge it or remove it. What do you thing?

P.S. about things in our discussion: I guess new improvements  is better to add with new PR. But I can't to start working on it before it is not merged.

**Comment by tsurdilo** [comment]
@Hasys 

- Getting rid of useless tabulations - good

- Bpmn2Unmarshalling and resorces movement to apropriate package - the changes to revisitBoundaryEventsPositions scare me a little. is there a way to create a test for this and have same test results before and after? Have you tested this within the editor to compare the before/after bpmn2/json for the boundary events?

- BZ#1275868 - Cannot add boundary event for user task if we have... - looks good

- Rebase fixes - not sure why this is needed

thanks!

**Comment by Hasys** [comment]
1.
2. It have the test here: Bpmn2UnmarshallingTestCase#testRevisitBoundaryEventsPositions 
3.
4. It because I moved the Bpmn2UnmarshallingTestCase class and appropriate resources to new directory and after that new resource was added to old place. So I moved it to new directory for better consistency.

**Comment by csadilek** [comment]
@tsurdilo Can you please plus one this or comment what you want changed? This has been pending for a while now.

**Comment by tsurdilo** [comment]
@csadilek @Hasys I tested the bpmn produced again and ran example process in the workbench it works as before so I will give this a go.

Btw would it be possible to squash the commits into a single one?

+1 (if @csadilek is OK with multiple commits here)

**Comment by csadilek** [comment]
@Hasys @tsurdilo I will squash the commits and merge.

**Comment by csadilek** [comment]
master: 6362b7770036071dcb87ab18db285c819b5c4e43

**Comment by triceo** [comment]
Thanks, @tsurdilo  and @csadilek !

**Pull request closed without merging**
