### PR TITLE
JBPM-5010: Swimlane lose it's documentation and tests refactoring

### PR DESCRIPTION
**Pull request by hasys**

### CODE REVIEW

**Comment by hasys** [comment]
Hi @jlindop, can you check Bpmn2JsonMarshaller refactorization? It is not using Bpmn2JsonUnmarshaller any more. If current implementation is OK I will cherry pick it to 6.4.x and then I will extend code coverage.

**Comment by jlindop** [comment]
Thanks @hasys   This looks great, with one minor issue - in the calls to assertEquals, the 2nd & 3rd parameters are the wrong way round (the declaration is assertEquals(String message, Object expected, Object actual))

**Comment by hasys** [comment]
@jlindop thank you for your review. Fix sent.

**Comment by jlindop** [comment]
Thanks
+1

**Comment by csadilek** [comment]
master: 18276115f8fc7170eabfa4bf370af64bd45bbae3 92f916af0f277597fb194a7864410fcc3c9e1f0b

**Pull request closed without merging**
