### PR TITLE
Fixes after IP BOM 7.0.0.CR4 upgrade

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
All PRs mentioned in https://github.com/errai/errai/pull/180 need to be merged together, at the same time.

**Comment by psiroky** [comment]
There two test failures related to the upgrade of JGit from 3.x to 4.x:
```
org.jbpm.designer.repository.VFSRepositoryGitFileSystemTest.testMoveDirectory
org.jbpm.designer.repository.VFSRepositoryGitFileSystemTest.testMoveEmptyDirectory
```

I was briefly looking into those, but I am not sure what's wrong. @jlindop or @tsurdilo could you please take a look?

**Comment by csadilek** [comment]
@psiroky I've amended your commit to UF here: https://github.com/csadilek/uberfire/commit/511c625981f4bb19d9c52eb02761172fed7cccff

See changes to JGitUtil.java. It fixes the test errors here (in designer), and of course, the UF tests still pass with these changes. So, updating the PR to UF and triggering a build should be enough.

**Comment by psiroky** [comment]
@csadilek UF PR updated. Thanks!

**Comment by csadilek** [comment]
+1

**Pull request merged**
