### PR TITLE
[6.5.x] JBPM-5249 - Higher level of automation when importing custom workItem…

### PR DESCRIPTION
**Pull request by tsurdilo**
…Handlers from a service repository

NOTE: this depends on jBPM PR  https://github.com/droolsjbpm/jbpm/pull/538

NOTE this fixes test fails for  BPMN2SyntaxCheckerTest

### CODE REVIEW

**Comment by tsurdilo** [comment]
need to retest once droolsjbpm/jbpm#538 has been merged

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
@csadilek ready to be merged

**Comment by csadilek** [comment]
@tsurdilo nope, it has conflicts and needs a plus one ;).

**Comment by tsurdilo** [comment]
@csadilek ok sure. my bad

@jomarko @jlindop please test when you can

**Comment by jomarko** [comment]
@tsurdilo sure, I am looking right now.

**Comment by jomarko** [comment]
Hello @tsurdilo , please can you amend your PR according to this one https://github.com/droolsjbpm/jbpm-designer/pull/374 ? Currently designer will be not opened at all because of an exception during bean initialization.

**Comment by tsurdilo** [comment]
@jomarko amended

**Comment by csadilek** [comment]
@tsurdilo still in conflict that needs to be resolved.

**Comment by tsurdilo** [comment]
@csadilek thanks!!! fixed

**Comment by jomarko** [comment]
@tsurdilo there occurred a problem with the first installation of the custom task. During the first installing deployment descriptor is not updated (only dependencies are added into pom.xml). During the second installing everything works as expected. I can reproduce it every time when I deploy workbench to clean application server. Then I create new project, business process and I install first custom task via Service Repository editor. When I install second custom task both pom.xml and DD are updated correctly. Can you please try to reproduce this issue?

**Comment by tsurdilo** [comment]
@jomarko just tried and cant -- https://streamable.com/9tqq
I have seen sometimes where the workbench takes its time to update the DD and the pom so maybe in your test after install wait a little and then open the editors (or try to reopen after a minute or so after first install) . maybe thats the same you see

**Comment by tsurdilo** [comment]
@jomarko should we test this 6.5.x specifically on the build servers instead of locally? we tested on master seemed fine and i worry these issues now maybe come from some misses in local builds or something. not sure. wdyt?

**Comment by jomarko** [comment]
@tsurdilo I agree with this option. But to be honest, I am not sure what exactly it means. Are there some servers where are deployed wars produced during jenkins build?

**Comment by tsurdilo** [comment]
@jomarko shouldnt it be available like any other release builds for testing?

**Comment by jomarko** [comment]
Hello @tsurdilo, I was investigating my issue more. The problem is quite simple. During the first custom task installation, 'if' on this line [1] evaluates to false and DD is not updated. I think that KieProject is not resolved on this line [2], because I can reproduce my issue always, if the 'Project Editor' was not opened before custom task installation.

After watching your video more times I think there are these steps necessary to reproduce the issue.

1. Start clean instance of eap7 (no war deployed there)
    This is not shown in the video.
2. Deploy there kie-wb-distributions/kie-wb/kie-wb-distribution-wars/target/kie-wb-6.5.0-SNAPSHOT-eap7.war
    In your video is the workbench url 'kie-wb'. I am not sure if you renamed the war or you used different one.
3. Be sure that 'Project Editor' was not opened. Then select and install custom task via 'Service Repository Editor'
4. Close the business process.
5. Check pom.xml and DD, pom.xml is updated, DD is not updated
6. Again install custom task via 'Service Repository Editor'
7. Both pom.xml and DD are updated

Please let me know if you are still unable to reproduce the issue.

[1]
https://github.com/droolsjbpm/jbpm-console-ng/pull/454/files#diff-e68407d8b34209e0cb9770b8b93e0eb4R91

[2]
https://github.com/droolsjbpm/jbpm-console-ng/pull/454/files#diff-e68407d8b34209e0cb9770b8b93e0eb4R86

**Comment by jlindop** [comment]
@tsurdilo  Jozef & I have been looking at it this morning and have come up with some precise reproduction steps:
- Build jbpm-designer with this PR
- Build jbpm-console-ng with PR452
- Build kie-wb-distributions/kie-wb, branch 6.5.x
- Create a fresh installation of EAP (I use 6.4.6) with kie-wb-6.5.0-SNAPSHOT-eap6_4.war in standalone/deployments
- Start EAP
- Logon to kie-workbench
- Select "Project Authoring"
- Authoring will open in the uf-playground/mortgages project
- Create a new BP called "BP1" in the default package
- Click the "Connect to a Service Repository" buton on the Designer button bar
- Enter the service repo address - on my machine this is: file:///home/jeremy/Documents/gitRepositories/droolsjbpm6.5.x/jbpm-designer/jbpm-designer-backend/src/test/resources/org/jbpm/designer/web/server/servicerepo   then click "Connect"
- Select "Microsoft Academy", then click "Yes" at the "Install Selected Item?" Prompt.
- Close the "Service Repository Connection" dialog.
- Click on "Open Project Editor"
- In the "Project Settings: Project General Settings" drop down, select "Deployment Descriptor".
- In the "Work Item handlers" section, "Microsoft Academy" is not listed, but it should be.

Hope this helps.

**Comment by tsurdilo** [comment]
not sure this is designer related. seems as if there is some differences in master and 6.5.x workbench code that is causing this. will investigate

**Comment by tsurdilo** [comment]
@jlindop did you have the jbpm console pr in your test environment for pr https://github.com/droolsjbpm/jbpm-console-ng/pull/454 which depends on this one ? We had a similar issue when testing with master where DD was not being updated and the issue was that this code was not added.

**Comment by jomarko** [comment]
After discussion with @tsurdilo and @jlindop I give +1

It will be easier to investigate the mentioned issue if this PR and jbpm-console-ng PR will be merged. Next the issue occurs only when pre-installed projects are used.

We keep the feature request jira still opened.

**Comment by jlindop** [comment]
@tsurdilo  Yes, I had https://github.com/droolsjbpm/jbpm-console-ng/pull/454 in my test environment - the PR number in the reproduction steps I gave was the wrong one.

**Pull request merged**
