### PR TITLE
RHBPMS-4482: Increase code coverage of ComboBoxViewImpl

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
This PR is dependent on #517 .

**Comment by jlindop** [comment]
@jomarko Awesome! Thanks for this Jozef (:

**Comment by jlindop** [comment]
@jomarko I've cherry-picked this test into #517  and #519 , so I'll close this PR when these have been merged. Thanks.

**Comment by jlindop** [comment]
@jomarko Will you close this if you can (I don't have permissions to close it). If not, we can ask one of the gatekeepers to do it. Thanks.

**Comment by triceo** [comment]
Closing as requested.

**Pull request closed without merging**
