### PR TITLE
JBPM-5459 - Add alternate ways to open the properties panel for nodes…

### PR DESCRIPTION
**Pull request by tsurdilo**
… and process properties

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jlindop 
ctrl-p opens/closes the property menu (right)
ctrl-m opens/closes the shape menu (left)

the shape menu icon opens/closes the property menu (right)

**Comment by jlindop** [comment]
@tsurdilo The shape menu icon works for User Tasks, but for other objects (e.g. Send Task, End Events, etc), it looks as though the new PropseditButton is overlaid on top of the ShowSourceViewButton. Maybe the showPropseditButton function needs to adjust the button group number, as is done in e.g. showSourceViewButton.
Also I'm not sure how to make ctrl-p work - for me this opens the Print dialog in Chrome and Firefox.

**Comment by tsurdilo** [comment]
@jlindop didnt have the problem with ctrl -p but will change that. also looking at the overlaying. thanks.

**Comment by tsurdilo** [comment]
@jlindop amended (use ctrl+shift+p and ctrl+shift+m for the shortcuts now)

**Comment by jlindop** [comment]
@tsurdilo  All working well now.
+1

**Pull request merged**
