### PR TITLE
JBPM-5007 - Process Documentation not contain Process Image

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jlindop : updated process image to be displayed correctly in FF. For Chrome it is as before. Please test on FF and Chrome. Thanks.

**Comment by tsurdilo** [comment]
@csadilek checks failed because an upstream issue. idk if should redo the pr or will the build be retried?

**Comment by psiroky** [comment]
jenkins retest this

**Comment by psiroky** [comment]
@tsurdilo see my previous comment. Adding comment like that re-triggers the build.

**Comment by jlindop** [comment]
+1  Tested and works fine.

**Comment by jlindop** [comment]
@tsurdilo  To fix for IE11, in docstructure.js, add on line 671:
var isIE = Object.hasOwnProperty.call(window, "ActiveXObject");
and change line 672 to:
if(isChrome || isIE) {

I've tested this on FF, Chrome and IE11.

**Comment by tsurdilo** [comment]
@jlindop amended. thanks
@psiroky thanks for showing me

**Comment by csadilek** [comment]
master: 56eff5c404cf3aeae26509390079e38b619c4b12

**Comment by jlindop** [comment]
+1 (after the PR has been closed, but never mind (-:  ) works fine in FF, Chrome and IE11

**Comment by csadilek** [comment]
@jlindop oops, my bad. Thought I saw a plus one ;-/.

**Pull request closed without merging**
