### PR TITLE
JBPM-5300 - Enable custom assignments for service tasks only when cus…

### PR DESCRIPTION
**Pull request by tsurdilo**
…tomeditors property is not empty (if it exists)

### CODE REVIEW

**Comment by tsurdilo** [comment]
jenkins build fails seem unrelated to designer completely

**Comment by jomarko** [comment]
@tsurdilo seems to be good. Just a question, what caused the decrease of globalAssets and defaultStuff?

**Comment by tsurdilo** [comment]
@jomarko not sure I understand your question. if you ask about why in case customeditor is defined in wid properties are shown as individual inputs/outputs rather than io/editor? 

We have customers that do not wish to use the data i/o editor for custom service tasks. rather they would like to plug in their own or make it simpler by just having each data input / output as individual properties on the panel -- then their users don't have to worry about knowing whats input whats output etc etc. Also then they can plug in their own really custom editor for each property as well if they would like as designer allows for fully custom editors for properties. 

HTH

**Comment by jomarko** [comment]
@tsurdilo thanks for comment. Sorry for my unclear question. Here it is again:

I was curious, why there are following two changes:
`assertEquals(31, globalAssets.size());` - `assertEquals(30, globalAssets.size());`
`assertEquals(3, defaultStuff.size());` - `assertEquals(2, defaultStuff.size());`

**Comment by tsurdilo** [comment]
@jomarko due to update to extend RepositoryBaseTest

**Comment by hasys** [comment]
Hi @tsurdilo,
> When customEditor is defined in wid, designer does not show data assignments as do other tasks ,but parses the wid and creates individual property for each input/output and that marshallers/unmarshallers also know how to deal w/ that situation.
HTH
It looks like individual properties shows only for input variables ('parameters' definitions in WID file). Individual properties for output variables ('results' definitions in WID file) is not appear in Task properties bar. Is it an expected behavior?

**Comment by tsurdilo** [comment]
@hasys yes iirc that was the expected behaviour with custom editors you deal with inputs only

**Comment by tsurdilo** [comment]
jenkins retest this

**Comment by jomarko** [comment]
Fail seems to be unrelated to this PR. The fix is exactly the same as the proposed in the email communication between me, @tsurdilo and @hasys. +1

**Comment by csadilek** [comment]
jenkins retest this.

**Pull request merged**
