### PR TITLE
Refactoring needed to test BZ#1271322

### PR DESCRIPTION
**Pull request by jomarko**
I feel that there is needed more refactoring to test mentioned bugzilla properly, but I think this is good start poitn.

### CODE REVIEW

**Comment by jomarko** [comment]
Please, do not merge yet. I am continuing in refactoring.

**Comment by jomarko** [comment]
I am done for this moment. I wanted to apply MVP pattern also on class AssignmentListItemWidget but I didn't succeed. I am open to any comments, suggestions, objections etc.

**Comment by jlindop** [comment]
Hi Jozef, Is this PR OK to merge now?  I'll take a look at it today, and am thinking I can make a separate PR for changes to AssignmentListItemWidget. Thanks for doing this refactoring & adding unit tests (-:

**Comment by jomarko** [comment]
@jlindop , yes, this PR is ready to merge. I think It would be great if you take refactor also AssignmentListItemWidget.

**Comment by jlindop** [comment]
+1   This is great. Thanks!

**Comment by csadilek** [comment]
Thanks!!

master: e817a6d1dfefce4bd4fa751c26ffd4753f961ec3

**Pull request closed without merging**
