### PR TITLE
BZ 1283135 - Changing of task type does not trigger Save dialogue

### PR DESCRIPTION
**Pull request by tsurdilo**
@csadilek master PR (js changes only)

### CODE REVIEW

**Comment by csadilek** [comment]
@tsurdilo might be best for @jlindop to review?

**Comment by jlindop** [comment]
+1  works fine

**Comment by csadilek** [comment]
Thanks.

master: ffa91fe9efde0de81405dee0a3095e9121a84913

**Comment by csadilek** [comment]
@tsurdilo @jlindop some very basic JS test would be nice to see despite our agreement that it's not strictly necessary ;). Maybe we can investigate jsMockito or something similar.

**Pull request closed without merging**
