### PR TITLE
Another round of fixes found by findbug.

### PR DESCRIPTION
**Pull request by Hasys**
@jlindop @tsurdilo Can I ask you to review this PR. It already had an conflict so in the future it will be even worse.

### CODE REVIEW

**Comment by tsurdilo** [comment]
Hi, couple comments:
* Bpmn2JsonUnmarshaller - 
changing if(beEntry != null && beEntry instanceof ErrorEventDefinition) { 
to 
 if(beEntry instanceof ErrorEventDefinition) {
and doing the null -check after can cause NPE if beEntry is null

* DesignerInjectionFilter is no longer used to those changes are not needed i think ( same for InjectionConfig and Beautifier)

* IOUtils.closeQuietly - are we sure we want to ignore exceptions here? 

* DesignerInjectionFilterTest - really nice to have but again the injection filter is not used so not sure if we need or not

**Comment by Hasys** [comment]
@tsurdilo thank you for your review.

Bpmn2JsonUnmarshaller:
I tried it locally and no NPE was thrown. Try this example:
public class Test {
    public static void main(String... args) {
        Object newObject = null;
        
        if (newObject instanceof Object) {
            System.out.println("It is always true except null");
        } else {
            System.out.println("It was null");
        }
    }
}

"It was null" was shown no exceptions thrown.

Can you provide example when it can cause NPE?

IOUtils.closeQuietly - yes, why not? It is just closing the stream in finally block.

DesignerInjectionFilter, DesignerInjectionFilterTest and others: so we can remove all this files from repository?

**Comment by Hasys** [comment]
@tsurdilo Update for NPE quote from Java Language Specification:
"At run time, the result of the instanceof operator is true if the value of the RelationalExpression is not null and the reference could be cast to the ReferenceType without raising a ClassCastException. Otherwise the result is false."

**Comment by tsurdilo** [comment]
@Hasys i think thats fine. i think having the null check further up as it was is fine but then do you need it again below? Up to you

**Comment by Hasys** [comment]
@tsurdilo I see.. I will fix that in the further commits. This PR is old enough to postpone it if no regressions or new problems found. I will work with Bpmn2Json[Un]marshaller intensively for nearest future and this thing I will fix firstly.

**Comment by tsurdilo** [comment]
Sounds great. Thank you for all your help. It is really appreciated!

**Comment by porcelli** [comment]
@tsurdilo is this good to merge?

**Comment by tsurdilo** [comment]
@porcelli I think @Hasys meant to incorporate these changes in his new PRs, @Hasys please let us know if I misunderstood something.

**Comment by Hasys** [comment]
@tsurdilo @porcelli you are right new changes will be in new PRs. So this PR is ready for merge.

**Comment by tsurdilo** [comment]
+1 then ;)

**Comment by porcelli** [comment]
https://github.com/droolsjbpm/jbpm-designer/commit/eed5685e6072ecc7165bd1d396d3100013070503

**Pull request closed without merging**
