### PR TITLE
JBPM-4815: Refactor AssignmentListItemWidget, creating separate Combo…

### PR DESCRIPTION
**Pull request by jlindop**
Refactor AssignmentListItemWidget, creating separate ComboBox class, and add Unit Tests which are enabled by this refactoring.

### CODE REVIEW

**Comment by jlindop** [comment]
@jomarko 
I've moved the URLEncode / URLDecode functions to StringUtils.java and added tests to ComboBoxTest which handle Strings / Numerics. I'll be adding more unit tests around quoting Strings / not-quoting numerics in a later commit.
Apologies for your earlier comment being removed - when I updated the PR, it got removed.

**Comment by csadilek** [comment]
Nice refactoring! Can someone @jomarko @tsurdilo do a quick review (and startup designer with the changes to verify) so I can merge?

**Comment by jomarko** [comment]
I compiled PR and DataIOAssignments works fine. Also code looks fine for me.
Some tests are a little bit weak from my point of view. But it is not problem. I am going to replace some selenium tests, which we have in QE team, with new mockito tests in community. So I will add some testcases in next days.

+1 from me.

**Comment by csadilek** [comment]
Thanks.

master: 05c6b38548be458c0c46be4a9216de8068f4d646

**Comment by jlindop** [comment]
Hi Jozef, 

I completely agree with your comment about some tests being weak (-: 
Thanks for saying you'll add some test cases. I'll also add more whenever I do work on the DataIOEditor. 

Regards 
Jeremy 

----- Original Message -----

**Pull request closed without merging**
